### ISSUE TITLE
Remember user settings

### ISSUE THREAD

**Issue by mehrtash** [QIICR/TCIABrowser#16]
Use qsettings to store the following settings:
- browser window size and position
- storage directory
- user specific APIs

**Comment by kirbyju** [comment]
@SL2027 - maybe looking into this qsettings thing could address the issue with the window not being sized properly to view the full Series table?  Even if we can't get it to open at an ideal size, if the user's resizing is saved after they correct it to fit their screen once that would be pretty nice.

I think the storage directory thing is still an issue.  If I change it to something other than the default it gets reset to the default when I open the app up next time.

I don't think the user specific API stuff is relevant anymore now that we're not using API keys.

**Comment by SL2027** [comment]
This is now fixed, I will include it in my next merge.
