### ISSUE TITLE
Improve download progress reporting

### ISSUE THREAD

**Issue by fedorov** [QIICR/TCIABrowser#30]
It appears that TCIA API now includes the capability to query the total series size (getSeriesSize endpoint, see https://wiki.cancerimagingarchive.net/display/Public/TCIA+Programmatic+Interface+%28REST+API%29+Usage+Guide). We should probably have progress bars for downloads report actual progress instead of "in progress".

**Comment by fedorov** [comment]
I didn't test it (I assume you did), but looks good to me (one typo found).

Thanks!

**Comment by mehrtash** [comment]
I fixed the typo and merged it.

Thanks,
Alireza

**Comment by fedorov** [comment]
Alireza can you update the version in the ExtensionIndex?

**Comment by mehrtash** [comment]
I made the pull request.

**Comment by fedorov** [comment]
Thanks!

Last thing :) Do you recall if it is using any recent features? If not, we should also update the 4.4 (or whatever release version it was included in) branch of the ExtensionIndex.

**Comment by mehrtash** [comment]
No it's not using any recent version. I will update 4.4.

**Comment by mehrtash** [comment]
Do I need to create a pull request for that?

**Comment by fedorov** [comment]
You just need to check out 4.4 branch of the ExtensionIndex, update and
make a pull request against 4.4 branch
