### ISSUE TITLE
Error message after download

### ISSUE THREAD

**Issue by hmeine** [QIICR/TCIABrowser#35]
I got the attached error message after every download (i.e., once for every file in a batch download): 
![bildschirmfoto 2016-01-07 um 17 28 56](https://cloud.githubusercontent.com/assets/462802/12184610/43b82218-b564-11e5-9d4b-010e62df397a.png)
Apparently, the download still succeeded, at least I see things in the DICOM database.

(Also, when I follow the instructions in the message and change the path to the local DB, the error message will still contain the old path, while the data obviously ends up in the right place.)

**Comment by hmeine** [comment]
Forgot to mention this was with the Slicer Nightly build from January 5th, in case it matters.

**Comment by fedorov** [comment]
@hmeine this should be fixed, if you download next nightly of Slicer, and update extension in stable, this should go away. As aside, this was just a warning, not affecting the functionality. Please let me know if you test and the problem persists. If I remember, I will test myself when I install the updated version.

Related commits:

https://github.com/Slicer/ExtensionsIndex/pull/1225
https://github.com/Slicer/ExtensionsIndex/pull/1224

**Comment by hmeine** [comment]
Confirmed, the message is gone. :-)
