### ISSUE TITLE
Add double click support for patients and studies table

### ISSUE THREAD

**Issue by fedorov** [QIICR/TCIABrowser#36]
... to parallel https://github.com/commontk/CTK/pull/627, as suggested by @hmeine

**Comment by kirbyju** [comment]
@fedorov, it looks like it's possible to double click on cells in the patient/study table and doing so allows the user to edit the contents of the cell in the table.  What is the intended purpose of doing this?  I don't understand why we'd want to let the users edit this info to be something other than what is actually in the database.

**Comment by fedorov** [comment]
It is most definitely not the intended behavior to have cells editable! It would be very good to make them read-only. I admit I do not recall what was the intent of this issue - it's been too long!
