### ISSUE TITLE
Only scalar volumes are loaded with scalar volume plugin

### ISSUE THREAD

**Issue by fedorov** [QIICR/TCIABrowser#37]
Instead, any series retrieved should go through the same "Load" process as done in DICOM Browser

**Comment by kirbyju** [comment]
@fedorov is this still an issue?  I think we'd need some explanation and assistance if there's something we should be doing to resolve this.

**Comment by fedorov** [comment]
Slicer has a a concept of [DICOM plugins](https://slicer.readthedocs.io/en/latest/user_guide/modules/dicom.html#dicom-plugins), which implement support for the specific types of DICOM objects. Scalar volume plugin handles the most commonly encountered case where DICOM series corresponds to a 3d volume. Other plugins support less common DICOM types, such as 4d volumes, RTSTRUCT, SEG, diffusion MRI, etc. Some of those plugins are included in the core application, some are available in Slicer extensions (such as DICOM SEG plugin, which is why you can't load DICOM SEG without first installing the QuantitativeReporting extension).

Currently, only scalar volume plugin is considered, see https://github.com/QIICR/TCIABrowser/blob/master/TCIABrowser/TCIABrowser.py#L856. I think it makes sense to test other plugins installed. It may be optimal to do this only if scalar volume plugin says that it is not going to be able to load a given content.

**Comment by kirbyju** [comment]
Very interesting! I was already thinking about how this type of thing could be a problem with the many DICOM SEG/RTSTRUCT files that are in TCIA and wasn't sure how we could best address that.  So we should be doing something similar to use these 3 extensions below?  Are there any others we should consider?  And is integrating them as simple as adding their plugin names to the list in the line that you linked to?

[Quantitative Reporting](https://github.com/QIICR/QuantitativeReporting#summary) extension reads and writes DICOM Segmentation Objects (label maps), structured reports, and parametric maps.

[SlicerRT](https://www.slicerrt.org/) extension reads and write DICOM Radiation Therapy objects (RT structure set, dose, image, plan, etc.) and provides tools for visualizing and analyzing them.

[LongitudinalPETCT](https://github.com/QIICR/LongitudinalPETCT#longitudinalpetct) extension reads all PET/CT studies for a selected patient and provides tools for tracking metabolic activity detected by PET tracers.

**Comment by kirbyju** [comment]
@fedorov we've set the Quantitative Reporting and SlicerRT extensions as dependencies and verified SEG/RTSTRUCT items load properly upon using the download + load option.  Can you let us know if we should be considering anything else or if this issue can be closed?

**Comment by fedorov** [comment]
I think it should be sufficient for now, and can be adjusted based on user feedback.
