### ISSUE TITLE
Add a button to delete cache

### ISSUE THREAD

**Issue by fedorov** [QIICR/TCIABrowser#39]
Currently, when a series fails to download, it is impossible to retry, since it is marked as downloaded in the TCIA Browser.

**Comment by fedorov** [comment]
@mehrtash please let me know when you will be able to look into this issue.

**Comment by fedorov** [comment]
@mehrtash - I still would like to see this done.

I was thinking, instead of adding a new button, perhaps you could just delete when cache checkbox is unchecked.

**Comment by mehrtash** [comment]
@fedorov fixed and made a pull request.

**Comment by mehrtash** [comment]
This is how the remove button looks:
![screenshot from 2017-03-18 19 40 03](https://cloud.githubusercontent.com/assets/2693004/24076886/035016ac-0c13-11e7-8a0f-0b63fcf1892c.png)

**Comment by fedorov** [comment]
Thanks! I will test and let you know.

I still think it would be nice to remove all of the cache on checkbox uncheck. It can be very inconvenient to delete cache for individual series one by one.

**Comment by mehrtash** [comment]
@fedorov I agree that it would be hard to delete individual images one by one. But the purpose of "cache server response" is different from deleting downloaded images.
We can add a "remove all" button or inform the user that he can download all the images by removing the "TCIALocal" folder in dicom database folder.

**Comment by fedorov** [comment]
I did not figure out how it works exactly, but what I know is that in case download fails for any reason, the series will be marked as downloaded, and the user has no means to reset it. There is some kind of cache for downloads. I think I tried to resolve this issue by removing TCIALocal folder, and it didn't help.
