### ISSUE TITLE
Histology Pathology Imaging

### ISSUE THREAD

**Issue by Olamiknight** [QIICR/TCIABrowser#70]
Hello, I am wondering if any of the studies had access to histopathology imaging. I can only seem to find CT, MRI, PET imaging.

**Comment by kirbyju** [comment]
TCIABrowser currently only supports queries against our DICOM database (NBIA).  We don't currently host any DICOM pathology data, but we do have a wide variety of pathology datasets in other formats.  You can find a list of all datasets at https://www.cancerimagingarchive.net/browse-collections/ and you can filter the results by typing "pathology" in the box just above the table.  You might also find [this notebook](https://github.com/kirbyju/TCIA_Notebooks/blob/main/TCIA_Aspera_CLI_Downloads.ipynb) useful if you want to download pathology data from a terminal.

Also, if you have any interest in extending TCIABrowser to support querying non-DICOM data using Aspera that would be amazing!

**Comment by Olamiknight** [comment]
I appreciate your quick response. Will look into the Aspera module to see if it applies to my project.
